#include "dns_updater.hpp"

#include <gtest/gtest.h>

#include <fstream>
#include <experimental/filesystem>

static constexpr auto DNS_ENTRY_1 = "DNS=1.2.3.4";
static constexpr auto DNS_ENTRY_2 = "DNS=5.6.7.8";

namespace fs = std::experimental::filesystem;

TEST(DnsUpdateTest, translate)
{
    std::stringstream src;
    src << DNS_ENTRY_1 << "\n"
        << DNS_ENTRY_2 << "\n";

    std::stringstream expected;
    expected << "### Generated by phosphor-networkd ###\n"
            << "nameserver 1.2.3.4\n"
             << "nameserver 5.6.7.8\n";

    std::stringstream dst;

    phosphor::network::dns::updater::updateDNSEntries(src, dst);

    // From actual file
    std::string dstEntry{};
    std::string dstContent{};
    while (std::getline(dst, dstEntry))
    {
        dstContent += dstEntry;
    }

    // From compare file
    std::string expectedEntry{};
    std::string expectedContent{};
    while (std::getline(expected, expectedEntry))
    {
        expectedContent += expectedEntry;
    }
    EXPECT_EQ(dstContent, expectedContent);
}
